apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: players-v2-0
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: apis.apiriders.cloud
      http:
        paths:
          - backend:
              serviceName: players-v2
              servicePort: 80
            path: /v2/.*
