apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: players-0
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              serviceName: players-service-0
              servicePort: 80
