apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bets-players-api-0
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              serviceName: bets-players-api-service-0
              servicePort: 80
